CREATE TABLE IF NOT EXISTS categories (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS compilation (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	pinned bool NULL,
	title varchar(50) NULL
);
CREATE TABLE IF NOT EXISTS compilation_events (
	id int8 NULL,
	compilation_id int8 NULL REFERENCES compilation (id),
	event_id int8 NULL REFERENCES event (id)
);
CREATE TABLE IF NOT EXISTS event (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	annotation varchar(2000) NULL,
	confirmed_requests int8 NULL,
	created_on timestamp NULL,
	description varchar(7000) NULL,
	event_date timestamp NULL,
	lat float4 NULL,
	lon float4 NULL,
	paid bool NULL,
	participant_limit int8 NULL,
	published_on timestamp NULL,
	request_moderation bool NULL,
	state varchar(255) NULL,
	title varchar(255) NULL,
	views int8 NULL,
	category_id int8 NULL REFERENCES categories (id),
	initiator_id int8 NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS request (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created timestamp NULL,
	status varchar(255) NULL,
	event_id int8 NULL REFERENCES event (id),
	requester_id int8 NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL,
	name varchar(255) NULL
);