version: '3.1'
services:
  stats-server:
    build: ./stats-service/server
    image: stats_service_image
    container_name: stats-servic
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: main_service_image
    container_name: main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
